server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: product-catalog
          uri: lb://product-catalog-service
          predicates:
            - Path=/products/**
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/customers/**
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/inventory/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# Resilience4j circuit breaker default configuration
resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 20
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
    instances:
      gatewayCircuitBreaker:
        baseConfig: default
