apiVersion: v1
kind: ConfigMap
metadata:
  name: product-catalog-config
  labels:
    app: product-catalog-service
data:
  SPRING_DATA_MONGODB_URI: "mongodb://mongo:27017/product_catalog_db"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-catalog-deployment
  labels:
    app: product-catalog-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-catalog-service
  template:
    metadata:
      labels:
        app: product-catalog-service
    spec:
      containers:
        - name: product-catalog-service
          # Replace this image with your registry/image:tag
          image: your-registry/product-catalog-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: product-catalog-config
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: product-catalog-service
  labels:
    app: product-catalog-service
spec:
  type: ClusterIP
  selector:
    app: product-catalog-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
