apiVersion: v1
kind: ConfigMap
metadata:
  name: order-processing-config
  labels:
    app: order-processing-service
data:
  SPRING_RABBITMQ_HOST: "rabbitmq"
  SPRING_RABBITMQ_PORT: "5672"
  SPRING_RABBITMQ_USERNAME: "guest"
  SPRING_RABBITMQ_PASSWORD: "guest"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-processing-deployment
  labels:
    app: order-processing-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-processing-service
  template:
    metadata:
      labels:
        app: order-processing-service
    spec:
      containers:
        - name: order-processing-service
          # Replace this image with your registry/image:tag
          image: your-registry/order-processing-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: order-processing-config
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: order-processing-service
  labels:
    app: order-processing-service
spec:
  type: ClusterIP
  selector:
    app: order-processing-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
